### ISSUE TITLE
Cache issue with code iso2 and iso3

### ISSUE THREAD

**Issue by Roms1383** [i-rocky/country-list-js#15]
When querying multiple times the same country, for example :

```js
const countries = require('country-list-js')
const first = countries.findByIso3('USA')
const second = countries.findByIso3('USA')
console.log(first)
console.log('---')
console.log(second)
```

The output is correct the first time but not the following ones, for example (please see value for **code** in both results) :
```js
{ name: 'United States',
  continent: 'North America',
  region: 'North America',
  capital: 'Washington',
  currency: { code: 'USD', symbol: '$', decimal: '2' },
  dialing_code: '1',
  provinces:
   [ { short: 'AL', name: 'Alabama', alias: null },
     { short: 'AK', name: 'Alaska', alias: null },
     { short: 'AZ', name: 'Arizona', alias: null },
     { short: 'AR', name: 'Arkansas', alias: null },
     { short: 'CA', name: 'California', alias: null },
     { short: 'CO', name: 'Colorado', alias: null },
     { short: 'CT', name: 'Connecticut', alias: null },
     { short: 'DC', name: 'District of Columbia', alias: null },
     { short: 'DE', name: 'Delaware', alias: null },
     { short: 'FL', name: 'Florida', alias: null },
     { short: 'FM', name: 'Micronesia', alias: null },
     { short: 'GA', name: 'Georgia', alias: null },
     { short: 'HI', name: 'Hawaii', alias: null },
     { short: 'ID', name: 'Idaho', alias: null },
     { short: 'IL', name: 'Illinois', alias: null },
     { short: 'IN', name: 'Indiana', alias: null },
     { short: 'IA', name: 'Iowa', alias: null },
     { short: 'KS', name: 'Kansas', alias: null },
     { short: 'KY', name: 'Kentucky', alias: null },
     { short: 'LA', name: 'Louisiana', alias: null },
     { short: 'ME', name: 'Maine', alias: null },
     { short: 'MD', name: 'Maryland', alias: null },
     { short: 'MA', name: 'Massachusetts', alias: null },
     { short: 'MI', name: 'Michigan', alias: null },
     { short: 'MN', name: 'Minnesota', alias: null },
     { short: 'MH', name: 'Marshall Islands', alias: null },
     { short: 'MS', name: 'Mississippi', alias: null },
     { short: 'MO', name: 'Missouri', alias: null },
     { short: 'MT', name: 'Montana', alias: null },
     { short: 'NE', name: 'Nebraska', alias: null },
     { short: 'NV', name: 'Nevada', alias: null },
     { short: 'NH', name: 'New Hampshire', alias: null },
     { short: 'NJ', name: 'New Jersey', alias: null },
     { short: 'NM', name: 'New Mexico', alias: null },
     { short: 'NY', name: 'New York', alias: null },
     { short: 'NC', name: 'North Carolina', alias: null },
     { short: 'ND', name: 'North Dakota', alias: null },
     { short: 'OH', name: 'Ohio', alias: null },
     { short: 'OK', name: 'Oklahoma', alias: null },
     { short: 'OR', name: 'Oregon', alias: null },
     { short: 'PA', name: 'Pennsylvania', alias: null },
     { short: 'PW', name: 'Palau', alias: null },
     { short: 'RI', name: 'Rhode Island', alias: null },
     { short: 'SC', name: 'South Carolina', alias: null },
     { short: 'SD', name: 'South Dakota', alias: null },
     { short: 'TN', name: 'Tennessee', alias: null },
     { short: 'TX', name: 'Texas', alias: null },
     { short: 'UT', name: 'Utah', alias: null },
     { short: 'VT', name: 'Vermont', alias: null },
     { short: 'VA', name: 'Virginia', alias: null },
     { short: 'WA', name: 'Washington', alias: null },
     { short: 'WV', name: 'West Virginia', alias: null },
     { short: 'WI', name: 'Wisconsin', alias: null },
     { short: 'WY', name: 'Wyoming', alias: null },
     { short: 'AS', name: 'American Samoa', alias: null },
     { short: 'GU', name: 'Guam', alias: null },
     { short: 'MP', name: 'Northern Mariana Islands', alias: null },
     { short: 'PR', name: 'Puerto Rico', alias: null },
     { short: 'UM',
       name: 'United States Minor Outlying Islands',
       alias: null },
     { short: 'VI', name: 'Virgin Islands', alias: null } ],
  code: { iso2: 'US', iso3: 'USA' } }
---
{ name: 'United States',
  continent: 'North America',
  region: 'North America',
  capital: 'Washington',
  currency:
   { code: { code: 'USD', symbol: '$', decimal: '2' },
     symbol: undefined,
     decimal: undefined },
  dialing_code: '1',
  provinces:
   [ { short: 'AL', name: 'Alabama', alias: null },
     { short: 'AK', name: 'Alaska', alias: null },
     { short: 'AZ', name: 'Arizona', alias: null },
     { short: 'AR', name: 'Arkansas', alias: null },
     { short: 'CA', name: 'California', alias: null },
     { short: 'CO', name: 'Colorado', alias: null },
     { short: 'CT', name: 'Connecticut', alias: null },
     { short: 'DC', name: 'District of Columbia', alias: null },
     { short: 'DE', name: 'Delaware', alias: null },
     { short: 'FL', name: 'Florida', alias: null },
     { short: 'FM', name: 'Micronesia', alias: null },
     { short: 'GA', name: 'Georgia', alias: null },
     { short: 'HI', name: 'Hawaii', alias: null },
     { short: 'ID', name: 'Idaho', alias: null },
     { short: 'IL', name: 'Illinois', alias: null },
     { short: 'IN', name: 'Indiana', alias: null },
     { short: 'IA', name: 'Iowa', alias: null },
     { short: 'KS', name: 'Kansas', alias: null },
     { short: 'KY', name: 'Kentucky', alias: null },
     { short: 'LA', name: 'Louisiana', alias: null },
     { short: 'ME', name: 'Maine', alias: null },
     { short: 'MD', name: 'Maryland', alias: null },
     { short: 'MA', name: 'Massachusetts', alias: null },
     { short: 'MI', name: 'Michigan', alias: null },
     { short: 'MN', name: 'Minnesota', alias: null },
     { short: 'MH', name: 'Marshall Islands', alias: null },
     { short: 'MS', name: 'Mississippi', alias: null },
     { short: 'MO', name: 'Missouri', alias: null },
     { short: 'MT', name: 'Montana', alias: null },
     { short: 'NE', name: 'Nebraska', alias: null },
     { short: 'NV', name: 'Nevada', alias: null },
     { short: 'NH', name: 'New Hampshire', alias: null },
     { short: 'NJ', name: 'New Jersey', alias: null },
     { short: 'NM', name: 'New Mexico', alias: null },
     { short: 'NY', name: 'New York', alias: null },
     { short: 'NC', name: 'North Carolina', alias: null },
     { short: 'ND', name: 'North Dakota', alias: null },
     { short: 'OH', name: 'Ohio', alias: null },
     { short: 'OK', name: 'Oklahoma', alias: null },
     { short: 'OR', name: 'Oregon', alias: null },
     { short: 'PA', name: 'Pennsylvania', alias: null },
     { short: 'PW', name: 'Palau', alias: null },
     { short: 'RI', name: 'Rhode Island', alias: null },
     { short: 'SC', name: 'South Carolina', alias: null },
     { short: 'SD', name: 'South Dakota', alias: null },
     { short: 'TN', name: 'Tennessee', alias: null },
     { short: 'TX', name: 'Texas', alias: null },
     { short: 'UT', name: 'Utah', alias: null },
     { short: 'VT', name: 'Vermont', alias: null },
     { short: 'VA', name: 'Virginia', alias: null },
     { short: 'WA', name: 'Washington', alias: null },
     { short: 'WV', name: 'West Virginia', alias: null },
     { short: 'WI', name: 'Wisconsin', alias: null },
     { short: 'WY', name: 'Wyoming', alias: null },
     { short: 'AS', name: 'American Samoa', alias: null },
     { short: 'GU', name: 'Guam', alias: null },
     { short: 'MP', name: 'Northern Mariana Islands', alias: null },
     { short: 'PR', name: 'Puerto Rico', alias: null },
     { short: 'UM',
       name: 'United States Minor Outlying Islands',
       alias: null },
     { short: 'VI', name: 'Virgin Islands', alias: null } ],
  code: { iso2: undefined, iso3: undefined } }
```

**Comment by ekkis** [comment]
yes.  I see the problem.  thanks for providing such clear analysis.  I will look into it but it may take me a bit

**Comment by Roms1383** [comment]
*  I actually made another test where I checkout your repository and try it from inside the cloned repository : it works fine
*  I add the dependency inside another repo : the bug is here

There might a problem with the packaged files on npm ?

**Comment by Roms1383** [comment]
```shell
diff index.js ../test-country-list/node_modules/country-list-js/index.js
```
gives :

```shell
70c70
<         return self.cache[prop][val];
---
>         return x(self.cache[prop][val]);
```

Looks like the culprit lies on line 70 :)

**Comment by ekkis** [comment]
oh... I think that means that the latest version has not been published.  the `return x()` is more correct as it seeks to preserve backward compatibility but we could introduce an ABC and abandon it

**Comment by Roms1383** [comment]
I don't know what the term ABC means @ekkis, but IMHO you should fix and re-publish it the easy way first, and maybe improve it afterwards 😀

**Comment by ekkis** [comment]
API-Breaking Change (also known as an IBC).  the problem is (according to your explanation) I cannot replicate it in my environment.  if you're correct about the line causing the problem, "fixing" it represents an IBC

**Comment by Roms1383** [comment]
> oh... I think that means that the latest version has not been published. the `return x()` is more correct as it seeks to preserve backward compatibility but we could introduce an ABC and abandon it

I think you're right

**Comment by ekkis** [comment]
sorry for the long delay.  I published today.  can you check again?

**Comment by Roms1383** [comment]
I made a test locally by upgrading to latest `"country-list-js": "^3.1.6"` (removing `node_modules` and `yarn.lock` beforehand), but I still get the exact same error and, looking at the sources, for the exact same reason.
Here is the updated `yarn.lock` :
```lock
...
country-list-js@^3.1.6:
  version "3.1.6"
  resolved "https://registry.yarnpkg.com/country-list-js/-/country-list-js-3.1.6.tgz#9e49d3ff002bff0adfb0b7acab49399b0e86e53c"
  integrity sha512-SjiQlWrFTn9Iu1rhpl/wRqV8I7kidlvSeVlsEeEWGTMAWAvDrAjq2ewMDaT+w+y5g/EwRp5Paf2qRWHdDumY+w==
  dependencies:
    micro "^9.3.3"
```

**Comment by ekkis** [comment]
ok.  I was able to find the issue and fix it.  release 3.1.7 should be good to go.  I added a test for this problem as well.  thank you for doing the analysis
